# ==========================
# Markdown 1
# ==========================
# # **Importing Required Libraries & Loading Dataset**


import pandas as pd
import numpy as np

df = pd.read_csv("/content/MiddleEast_dataset.csv")

# ==========================
# Markdown 2
# ==========================
# # **Dataset Overview**
# 
# Before preprocessing, it is important to understand the structure of the dataset.
# 
# This section provides information about:
# - Number of records
# - Number of features
# - Data types
# - Missing values
# 
# Understanding the dataset helps identify potential data quality issues that need to be addressed before model development.
# yeah

# Display dataset structure and identify missing values
df.info()

df.describe()

# ==========================
# Markdown 3
# ==========================
# # **DATA CLEANING AND PREPROCESSING**
# 
# This section performs:
# - Duplicate value analysis
# - Missing value analysis
# - Missing value treatment
# 
# Ensuring data quality improves model reliability and prediction performance.

# Check for duplicate project records
print("Number of duplicate rows:", df.duplicated().sum())

# Check number of missing values in each column
df.isnull().sum()

# Remove missing Emirate_Region
df = df.dropna(subset=["Emirate"])

# Replace missing values with the median
df["Budget"] = df["Budget"].fillna(
    df["Budget"].median()
)

df["Labor_Hours"] = df["Labor_Hours"].fillna(
    df["Labor_Hours"].median()
)

# ==========================
# Markdown 4
# ==========================
# **Data Conversion and Feature Engineering**
# 
# Project dates are converted into datetime format to enable time-based calculations and for feature engineering.
# 
# Converting date columns allows extraction of useful scheduling information that may influence project delays.

#Check data taypes
df.dtypes

# Convert date columns into datetime format for time calculations
df["Start_Date"] = pd.to_datetime(df["Start_Date"],dayfirst=True)
df["End_Date"] = pd.to_datetime(df["End_Date"],dayfirst=True)
df["Actual_End_Date"] = pd.to_datetime(df["Actual_End_Date"],dayfirst=True)

# ==========================
# Markdown 5
# ==========================
# **Target Variable Creation**
# 
# A binary target variable named On_Time_Status is created to classify project outcomes.
# 
# Classification Rules:
# - 0 = Project completed on time
# - 1 = Project delayed
# 
# The target variable is generated by comparing the Actual_End_Date with the planned End_Date.
# 
# This variable serves as the prediction target for the machine learning model.


# Create binary target variable:
# 0 = On Time
# 1 = Delayed
df['Timeline_Performance'] = np.where(
    df['Actual_End_Date'] > df['End_Date'],
    1,
    0
)

print(df['Timeline_Performance'].value_counts())

# ==========================
# Markdown 6
# ==========================
# **Feature Engineering**
# 
# Additional features are created from project dates to improve predictive performance.
# 
# Generated Features:
# - Planned_Duration
# - Start_Month
# - Start_DayOfWeek
# 
# These features provide scheduling information that may help identify patterns associated with project delays.

# Calculate planned project duration in days
df['Planned_Duration'] = (df['End_Date'] - df['Start_Date']).dt.days

# Extract month from project start date
df['Start_Month'] = df['Start_Date'].dt.month

# Extract day of week from project start date
df['Start_DayOfWeek'] = df['Start_Date'].dt.dayofweek

# ==========================
# Markdown 7
# ==========================
# ## **Feature** **Selection**
# 
# Certain columns are removed because they are either identifiers, contain information unavailable at prediction time, or may introduce data leakage.
# 
# Examples include:
# - Project_ID
# - Project_Name
# - Actual_End_Date
# - Cost
# - Cost_Variance
# 
# Only relevant predictive features are retained for model training.

# Remove identifiers and columns that may cause data leakage
df = df.drop(columns=[
    'Project_ID',
    'Project_Name',
    'Actual_End_Date',
    'Task_Status',
    'Cost',
    'Cost_Variance',
    'Start_Date',
    'End_Date'
])

print(df.head())

# ==========================
# Markdown 8
# ==========================
# ## **Encoding Categorical Variables**
# 
# Machine learning algorithms require numerical input.
# 
# Categorical variables such as:
# - Emirate
# - Type_of_Work
# - Contractor
# 
# are converted into numerical representations using Label Encoding.
# 
# This allows the Random Forest model to process categorical information effectively.

# Convert categorical variables into numerical values
from sklearn.preprocessing import LabelEncoder

le_emirate = LabelEncoder()
le_work = LabelEncoder()
le_contractor = LabelEncoder()

df['Emirate'] = le_emirate.fit_transform(df['Emirate'])
df['Type_of_Work'] = le_work.fit_transform(df['Type_of_Work'])
df['Contractor'] = le_contractor.fit_transform(df['Contractor'])

# ==========================
# Markdown 9
# ==========================
# ## **Defining Features and Target Variables**
# 
# The dataset is separated into:
# 
# - Feature matrix (X)
# - Target variable (y)
# 
# The feature matrix contains all predictor variables, while the target variable contains the project delay classification.

# Separate predictor variables and target variable
X = df.drop('Timeline_Performance', axis=1)

y = df['Timeline_Performance']

# ==========================
# Markdown 10
# ==========================
# ## **Train-Test Split**
# 
# The dataset is divided into training and testing sets.
# 
# - Training Set: Used to train the model.
# - Testing Set: Used to evaluate performance on unseen data.
# 
# An 80/20 split is used with stratified sampling to maintain the original class distribution.

from sklearn.model_selection import train_test_split

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(df['Timeline_Performance'].value_counts())
print("Training Set:", X_train.shape)
print("Testing Set:", X_test.shape)

# ==========================
# Markdown 11
# ==========================
# **Base Random Forest Model Development**
# 
# A Random Forest Classifier is used to predict project delays.
# 
# Random Forest is an ensemble learning algorithm that combines multiple decision trees to improve accuracy and reduce overfitting.
# 
# The model is trained using historical ERP project data to learn patterns associated with project delays.

# Train Random Forest classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)


# Make predictions on unseen test data
y_pred = rf.predict(X_test)

# Predict probabilities
probs = rf.predict_proba(X_test)

# Extract the probability of the "Delayed" and "On-time" class
ontime_prob = probs[:,0]
delay_prob = probs[:,1]

# Display prediction results for the first 6 projects in the test set
for i in range(6):

    # Convert numeric prediction to a readable label
    status = "Delayed" if y_pred[i] == 1 else "On-Time"

    # Assign risk level based on delay probability
    if delay_prob[i] < 0.30:
        risk = "Low"

    elif delay_prob[i] < 0.70:
        risk = "Medium"

    else:
        risk = "High"

    # Print prediction results
    print("Project", i+1)
    print("Prediction:", status)
    print("On-Time Probability:", round(ontime_prob[i]*100,2), "%")
    print("Delay Probability:", round(delay_prob[i]*100,2), "%")
    print("Risk Level:", risk)
    print()

# ==========================
# Markdown 12
# ==========================
# # **Model Evaluation** - (Accuracy, Classification Report)
# 
# 
# Initial Model Evaluation
# 
# The trained model is evaluated using classification metrics:
# 
# - Accuracy
# - Precision
# - Recall
# - F1-Score
# 
# These metrics provide insight into how effectively the model distinguishes between delayed and on-time projects.

#Evaluate the model
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ==========================
# Markdown 13
# ==========================
# # **Feature Importance Analysis**
# 
# One advantage of Random Forest is its ability to measure the importance of each feature.
# 
# Feature importance scores help identify which project characteristics contribute most to delay predictions.
# 
# This analysis provides valuable business insights for project managers.

#feature importance
import pandas as pd

# Extract feature importance scores from Random Forest
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

# ==========================
# Markdown 14
# ==========================
# # **Feature Importance Visualization**
# 
# The feature importance scores are visualized using a horizontal bar chart.
# 
# Features with higher scores have a greater influence on model predictions.
# 
# This helps interpret the model and identify key drivers of project delays.

import matplotlib.pyplot as plt

importance = importance.sort_values(
    by='Importance',
    ascending=True
)

plt.figure(figsize=(8,5))
plt.barh(
    importance['Feature'],
    importance['Importance']
)

plt.xlabel('Importance Score')
plt.ylabel('Features')
plt.title('Feature Importance - Random Forest')
plt.tight_layout()
plt.show()

# ==========================
# Markdown 15
# ==========================
# # **Cross Validation**
# 
# Cross validation is performed to assess the stability and generalization ability of the model.
# 
# The dataset is divided into multiple folds, and the model is trained and evaluated repeatedly.
# 
# This provides a more reliable estimate of model performance compared to a single train-test split.

#Cross validation
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rf,
    X,
    y,
    cv=5,
    scoring='accuracy'
)

print("Cross Validation Scores:")
print(scores)

print("\nAverage Accuracy:")
print(scores.mean())

# ==========================
# Markdown 16
# ==========================
# # **Hyperparameter Tuning**
# 
# Grid Search Cross Validation is used to identify the optimal Random Forest parameters.
# 
# Parameters tuned include:
# - Number of trees
# - Maximum tree depth
# - Minimum samples split
# - Minimum samples leaf
# 
# The goal is to maximize model performance while minimizing overfitting.

#Hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters:")
print(grid.best_params_)

print("\nBest Cross Validation Score:")
print(grid.best_score_)

best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)

# ==========================
# Markdown 17
# ==========================
# # **Confusion Matrix**
# 
# The confusion matrix summarizes the model's classification results.
# 
# It shows:
# - Correctly predicted on-time projects
# - Correctly predicted delayed projects
# - False positives
# - False negatives
# 
# This provides a detailed understanding of classification errors.

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ==========================
# Markdown 18
# ==========================
# # **ROC Curve and AUC Analysis**
# 
# The ROC Curve evaluates the model's ability to distinguish between delayed and on-time projects across different classification thresholds.
# 
# The Area Under the Curve (AUC) measures the model's overall discriminative power.
# 
# Higher AUC values indicate stronger classification performance.

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['On Time', 'Delayed'],
    yticklabels=['On Time', 'Delayed']
)

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Random Forest')
plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Get prediction probabilities
y_prob = best_rf.predict_proba(X_test)[:, 1]

# Calculate ROC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# Calculate AUC
roc_auc = auc(fpr, tpr)

print("AUC Score:", roc_auc)

# Plot ROC Curve
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.3f}')
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Random Forest')
plt.legend()
plt.show()

# ==========================
# Markdown 19
# ==========================
# ### **Predicted Probability Distribution**
# 
# While classification metrics such as Accuracy, Precision, Recall, and F1-Score tell us how well the model performs overall, they do not show how confident the model is when making predictions.
# 
# Random Forest provides a probability score for each class. Instead of simply predicting whether a project is "On Time" or "Delayed", the model estimates the probability that a project will be delayed.
# 
# This visualization compares the predicted delay probabilities for:
# 
# - Actual On Time projects
# - Actual Delayed projects
# 
# A well-performing model should assign:
# 
# - Low delay probabilities to projects that are actually On Time.
# - High delay probabilities to projects that are actually Delayed.
# 
# The greater the separation between the two distributions, the better the model is at distinguishing between the two classes.

# Obtain the predicted probability of the positive class (Delayed = 1)
# predict_proba() returns probabilities for both classes:
# Column 0 = Probability of On Time
# Column 1 = Probability of Delayed
y_prob = best_rf.predict_proba(X_test)[:, 1]

# Plot the probability distribution separately for actual On Time vs actual Delayed cases
plt.hist(y_prob[y_test==0], bins=20, alpha=0.5, label='Actual: On Time')
plt.hist(y_prob[y_test==1], bins=20, alpha=0.5, label='Actual: Delayed')
plt.xlabel('Predicted Probability of Delay')
plt.ylabel('Number of Projects')
plt.title('Predicted Probability Distribution')
plt.legend()
plt.show()
